//! The command line tool. The implementation lives in the library so that the
//! binary and the tests can share it.

#[cfg(feature = "gui")]
pub mod gui;
pub mod report;

/// The license of aliexpress-cli itself (MIT), for `--license`.
pub const LICENSE: &str = include_str!("../../../LICENSE");

/// The licenses of the libraries compiled into the binary, embedded at build
/// time. Generated by `scripts/generate-third-party-notices.sh`; see the tests
/// in `tests/third_party_notices.rs` for what keeps it from going stale.
pub const THIRD_PARTY_NOTICES: &str = include_str!("../../../THIRD-PARTY-NOTICES.txt");
