#!/usr/bin/env bash
# Writes the licenses of the libraries compiled into the shipped binaries to
# THIRD-PARTY-NOTICES.txt. Run it again and commit the result whenever a
# dependency is added or upgraded: the tests in
# crates/aliexpress-cli/tests/third_party_notices.rs fail on a stale file.
#
# Needs cargo-about (`cargo install cargo-about --locked --features cli`) and jq.
# The configuration is crates/aliexpress-cli/about.toml, the layout
# crates/aliexpress-cli/about.hbs.
#
# Two binaries ship: macOS (aarch64, default features, so with the Tauri window)
# and Linux (x86_64, --no-default-features, command line only). The list is
# generated from the macOS build, which is the larger one, and the Linux build is
# then checked against it: should a Linux-only crate ever appear, this script
# fails instead of leaving it out.
#
# The UI (crates/aliexpress-cli/ui) is plain HTML and JavaScript with no
# third-party packages, so there is no JavaScript section.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="THIRD-PARTY-NOTICES.txt"
MANIFEST="crates/aliexpress-cli/Cargo.toml"

if ! cargo about --version >/dev/null 2>&1; then
  echo "Error: cargo-about is not installed. Run: cargo install cargo-about --locked --features cli" >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "Error: jq is not installed." >&2
  exit 1
fi

# Written next to the output and moved into place, so that a run which fails
# partway leaves the old file rather than half of a new one (a mv from /tmp on
# another file system is a copy).
TMP=$(mktemp "${OUT}.XXXXXX")
LINUX_JSON=$(mktemp "${OUT}.linux.XXXXXX")
trap 'rm -f "$TMP" "$LINUX_JSON"' EXIT

{
  cat <<'HEADER'
THIRD-PARTY NOTICES

aliexpress-cli bundles the open source libraries listed below. Each entry gives
the license, the packages it applies to, and the license text as shipped by the
package. Generated by scripts/generate-third-party-notices.sh; do not edit by hand.

The list is that of the macOS build, which has the desktop window. The Linux
build is command line only and uses a subset of these crates.

################################################################################
# Rust crates (compiled into the binary)
################################################################################

HEADER

  # --fail: a crate whose license cannot be worked out fails the run instead of
  # being left out with a warning.
  cargo about generate --manifest-path "$MANIFEST" --locked --fail \
    crates/aliexpress-cli/about.hbs
} > "$TMP"

cargo about generate --manifest-path "$MANIFEST" --locked --fail --format json \
  --target x86_64-unknown-linux-gnu --no-default-features > "$LINUX_JSON"

# "<name> <version>" of every crate, one per line. In the text the crates are
# the "  <name> <version> (<repository>)" lines under "Used by:".
listed=$(awk '/^  [^ ]+ [^ ]+( \(.*\))?$/ { print $1, $2 }' "$TMP" | sort -u)
linux=$(jq -r '.licenses[].used_by[].crate | "\(.name) \(.version)"' "$LINUX_JSON" | sort -u)
missing=$(comm -13 <(printf '%s\n' "$listed") <(printf '%s\n' "$linux"))
if [ -n "$missing" ]; then
  echo "Error: the Linux build has crates the macOS list does not:" >&2
  echo "$missing" >&2
  echo "Add x86_64-unknown-linux-gnu handling to this script." >&2
  exit 1
fi

if grep -qE '^  aliexpress-(cli|core) ' "$TMP"; then
  echo "Error: the workspace's own crates are in the list; are they still publish = false?" >&2
  exit 1
fi

mv "$TMP" "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
